#### Data Science

Importing data in panda


fix data


        -set symbol to INFY+'-'+Series

        -remove series

        -find average of all half years

        -examine NaN and fix it

Visualisation

In [5]:
import pandas as pd
import numpy as np
# import matplotlib as mpl
# import matplotlib.pyplot as plt
import re
INFYdf=pd.read_csv('INFY.csv')
print("Data imported")
INFYdf

Data imported

,Date,Symbol,Series,Prev Close,Open,High,Low,Last,Close,VWAP,Volume,Turnover,Trades,Deliverable Volume,%Deliverble
0,2000-01-03,INFOSYSTCH,EQ,14467.75,15625.00,15625.20,15625.00,15625.20,15625.20,15625.18,5137,8.026657e+12,NaN,NaN,NaN
1,2000-01-04,INFOSYSTCH,EQ,15625.20,16800.00,16875.25,16253.00,16875.25,16855.90,16646.38,56186,9.352937e+13,NaN,NaN,NaN
2,2000-01-05,INFOSYSTCH,EQ,16855.90,15701.00,16250.00,15507.45,15507.45,15507.45,15786.38,164605,2.598516e+14,NaN,NaN,NaN
3,2000-01-06,INFOSYSTCH,EQ,15507.45,15256.65,15300.00,14266.85,14266.85,14266.85,14462.82,81997,1.185908e+14,NaN,NaN,NaN
4,2000-01-07,INFOSYSTCH,EQ,14266.85,13125.50,13125.50,13125.50,13125.50,13125.50,13125.50,7589,9.960942e+12,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5301,2021-04-26,INFY,EQ,1333.80,1332.25,1351.30,1321.00,1345.00,1343.55,1343.19,7088606,9.521361e+14,130375.0,4218129.0,0.5951
5302,2021-04-27,INFY,EQ,1343.55,1346.00,1353.00,1340.15,1347.50,1348.50,1346.89,3636115,4.897445e+14,145974.0,1871084.0,0.5146
5303,2021-04-28,INFY,EQ,1348.50,1358.00,1359.50,1344.60,1355.80,1356.00,1353.45,4879234,6.603778e+14,137376.0,2857134.0,0.5856
5304,2021-04-29,INFY,EQ,1356.00,1368.00,1369.00,1351.40,1356.00,1356.35,1360.05,5412357,7.361090e+14,119277.0,3130945.0,0.5785
5305,2021-04-30,INFY,EQ,1356.35,1346.30,1373.90,1345.90,1348.60,1354.35,1361.16,8354677,1.137203e+15,131718.0,5408113.0,0.6473

In [6]:
print(INFYdf.columns)

Index(['Date', 'Symbol', 'Series', 'Prev Close', 'Open', 'High', 'Low', 'Last',
       'Close', 'VWAP', 'Volume', 'Turnover', 'Trades', 'Deliverable Volume',
       '%Deliverble'],
      dtype='object')

In [7]:
INFYdf['Symbol'] = 'INFY-' + INFYdf['Series']
INFYdf.drop('Series', axis=1, inplace=True)
INFYdf

# INFYdf.isna().sum()
# INFYdf.fillna(INFYdf.mean(), inplace=True)

,Date,Symbol,Prev Close,Open,High,Low,Last,Close,VWAP,Volume,Turnover,Trades,Deliverable Volume,%Deliverble
0,2000-01-03,INFY-EQ,14467.75,15625.00,15625.20,15625.00,15625.20,15625.20,15625.18,5137,8.026657e+12,NaN,NaN,NaN
1,2000-01-04,INFY-EQ,15625.20,16800.00,16875.25,16253.00,16875.25,16855.90,16646.38,56186,9.352937e+13,NaN,NaN,NaN
2,2000-01-05,INFY-EQ,16855.90,15701.00,16250.00,15507.45,15507.45,15507.45,15786.38,164605,2.598516e+14,NaN,NaN,NaN
3,2000-01-06,INFY-EQ,15507.45,15256.65,15300.00,14266.85,14266.85,14266.85,14462.82,81997,1.185908e+14,NaN,NaN,NaN
4,2000-01-07,INFY-EQ,14266.85,13125.50,13125.50,13125.50,13125.50,13125.50,13125.50,7589,9.960942e+12,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5301,2021-04-26,INFY-EQ,1333.80,1332.25,1351.30,1321.00,1345.00,1343.55,1343.19,7088606,9.521361e+14,130375.0,4218129.0,0.5951
5302,2021-04-27,INFY-EQ,1343.55,1346.00,1353.00,1340.15,1347.50,1348.50,1346.89,3636115,4.897445e+14,145974.0,1871084.0,0.5146
5303,2021-04-28,INFY-EQ,1348.50,1358.00,1359.50,1344.60,1355.80,1356.00,1353.45,4879234,6.603778e+14,137376.0,2857134.0,0.5856
5304,2021-04-29,INFY-EQ,1356.00,1368.00,1369.00,1351.40,1356.00,1356.35,1360.05,5412357,7.361090e+14,119277.0,3130945.0,0.5785
5305,2021-04-30,INFY-EQ,1356.35,1346.30,1373.90,1345.90,1348.60,1354.35,1361.16,8354677,1.137203e+15,131718.0,5408113.0,0.6473

In [8]:
INFYdf['Date'] = pd.to_datetime(INFYdf['Date'])
INFYdf['half_year'] = INFYdf['Date'].dt.year.astype(str) + '-' + ((INFYdf['Date'].dt.month-1)//6 + 1).astype(str)
INFYdf.groupby('half_year').mean()
# INFYdf

C:\Users\bhask\AppData\Local\Temp\ipykernel_9984\61700857.py:3: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  INFYdf.groupby('half_year').mean()

,Prev Close,Open,High,Low,Last,Close,VWAP,Volume,Turnover,Trades,Deliverable Volume,%Deliverble
half_year,,,,,,,,,,,,
2000-1,9297.043548,9280.081452,9583.609274,8932.296371,9243.237097,9247.387500,9270.009113,2.658739e+05,2.238949e+14,NaN,NaN,NaN
2000-2,7462.186111,7460.341667,7603.929762,7301.347222,7444.601587,7441.421825,7449.295794,6.463773e+05,4.741746e+14,NaN,NaN,NaN
2001-1,4766.869600,4766.485200,4886.624800,4616.370800,4749.563200,4751.306000,4747.946880,6.236268e+05,3.033834e+14,NaN,NaN,NaN
2001-2,3402.759350,3399.408537,3487.860976,3313.252439,3407.211789,3405.484553,3404.624634,6.369356e+05,2.153841e+14,NaN,NaN,NaN
2002-1,3763.587698,3772.546429,3836.448810,3695.958333,3755.093651,3757.211508,3763.117460,5.529193e+05,2.102129e+14,NaN,9.079281e+04,0.161993
2002-2,3739.113200,3739.970400,3796.016800,3697.415600,3751.966000,3751.056000,3747.491520,7.170975e+05,2.767311e+14,NaN,9.537322e+04,0.127376
2003-1,3713.304435,3712.912097,3769.458871,3641.053629,3702.319355,3701.213306,3705.634597,8.677398e+05,3.113098e+14,NaN,1.461501e+05,0.149521
2003-2,4290.572692,4311.273077,4385.661538,4224.446538,4304.666154,4308.193462,4310.319077,6.499995e+05,2.707547e+14,NaN,1.321396e+05,0.198422
2004-1,5266.230400,5304.703600,5383.691600,5181.202400,5267.987600,5265.905600,5273.871440,4.781252e+05,2.520617e+14,NaN,1.265641e+05,0.258970
2004-2,1772.613566,1743.610078,1764.759690,1726.236822,1746.348062,1746.005814,1745.936822,1.243402e+06,2.136886e+14,NaN,4.436306e+05,0.355143
2005-1,2127.284921,2128.972619,2159.827381,2099.082143,2128.468651,2129.400397,2128.761429,1.021471e+06,2.152071e+14,NaN,4.461473e+05,0.427758
2005-2,2523.581600,2528.312400,2559.087600,2497.395600,2528.519200,2528.690400,2529.397680,8.935025e+05,2.259821e+14,NaN,4.365614e+05,0.480140
2006-1,2951.177419,2961.538710,3002.883871,2908.441532,2951.327823,2951.839516,2953.625081,1.037905e+06,3.058601e+14,NaN,6.042731e+05,0.569490
2006-2,2032.001984,2026.900397,2048.478175,1999.936905,2025.639286,2025.357937,2025.109524,1.192880e+06,2.428886e+14,NaN,7.250245e+05,0.599249
2007-1,2093.545492,2093.540574,2119.439754,2062.858607,2089.910246,2090.981967,2091.955574,1.426462e+06,2.958398e+14,NaN,9.044619e+05,0.632266
2007-2,1832.932677,1835.321654,1862.696457,1802.833071,1830.293701,1831.679528,1832.253858,1.628021e+06,2.983926e+14,NaN,1.126340e+06,0.688394
2008-1,1638.862195,1641.786179,1677.127642,1603.572764,1639.948780,1638.593089,1639.506179,1.717906e+06,2.835033e+14,NaN,1.045162e+06,0.607532
2008-2,1453.349593,1454.065854,1486.582927,1411.628049,1448.569106,1448.297967,1447.631789,1.910156e+06,2.752133e+14,NaN,1.025180e+06,0.525167
2009-1,1412.869915,1411.379237,1445.611017,1385.179237,1417.695763,1418.472034,1415.165169,1.800552e+06,2.537808e+14,NaN,1.005517e+06,0.552569
2009-2,2196.825600,2198.071600,2228.714400,2170.202800,2203.309600,2203.422400,2201.078800,1.297032e+06,2.817166e+14,NaN,7.689372e+05,0.577249
2010-1,2646.162195,2646.204065,2675.317480,2616.642683,2648.145935,2647.706098,2645.643496,1.044177e+06,2.761772e+14,NaN,6.000518e+05,0.579403
2010-2,2973.901550,2973.968992,3005.282558,2948.341085,2977.122093,2978.953876,2978.148915,9.075390e+05,2.709024e+14,NaN,5.552310e+05,0.612427
2011-1,3033.346774,3028.890726,3061.535887,2999.142742,3028.552016,3029.054032,3030.156452,1.223800e+06,3.697722e+14,47959.545455,7.316123e+05,0.596916
2011-2,2626.828455,2624.223171,2657.985772,2591.548780,2626.236585,2625.667480,2624.226341,1.350122e+06,3.487034e+14,61342.016260,7.166580e+05,0.528677
2012-1,2634.499213,2632.800000,2660.791339,2601.798425,2630.627559,2632.464173,2631.090315,1.249847e+06,3.234839e+14,62579.496063,7.466723e+05,0.592506
2012-2,2380.545161,2376.503629,2400.607661,2352.675403,2377.880645,2379.008871,2378.233145,1.050472e+06,2.494888e+14,54000.201613,6.462553e+05,0.625748
2013-1,2604.377600,2605.291200,2630.676400,2581.018400,2605.073600,2605.818800,2605.718880,1.293778e+06,3.350361e+14,70045.008000,7.876923e+05,0.660338
2013-2,3112.575200,3115.277600,3149.086800,3092.094400,3120.822000,3120.469600,3120.882800,1.123136e+06,3.488248e+14,65308.304000,7.395751e+05,0.672954
2014-1,3387.078049,3387.223171,3418.890650,3352.339837,3385.777642,3385.207317,3385.049675,1.220571e+06,4.098361e+14,73036.951220,8.274530e+05,0.682373
2014-2,3414.166942,3398.954132,3435.543388,3367.576033,3403.281818,3403.563636,3401.816116,1.726809e+06,5.029343e+14,68271.785124,1.214359e+06,0.651676
2015-1,2024.539837,2020.359350,2039.433333,1994.358537,2016.784553,2016.505691,2016.117073,2.247633e+06,4.423697e+14,80539.495935,1.512132e+06,0.687108
2015-2,1085.978800,1088.172000,1100.670400,1073.241600,1086.884400,1086.947200,1087.637840,3.704759e+06,4.047601e+14,104616.384000,2.361182e+06,0.637899
2016-1,1170.978455,1172.090244,1184.607317,1159.202846,1171.434553,1171.510163,1171.638780,3.238293e+06,3.797532e+14,95247.943089,2.081948e+06,0.643802
2016-2,1031.693548,1032.004435,1041.020968,1020.671371,1030.304435,1030.401613,1030.840242,3.599711e+06,3.717639e+14,103641.790323,2.457866e+06,0.698923
2017-1,971.535366,971.797154,980.430894,961.327642,970.886585,970.925203,970.569187,3.871921e+06,3.748340e+14,102701.455285,2.589336e+06,0.675220
2017-2,953.516800,955.194000,964.353200,945.602800,954.130800,954.368800,954.810160,5.915238e+06,5.575365e+14,121680.992000,3.658896e+06,0.657381
2018-1,1164.166129,1163.917339,1177.875000,1153.526613,1165.943548,1166.304435,1166.701532,4.585599e+06,5.333612e+14,122896.016129,2.948870e+06,0.644910
2018-2,934.399590,931.022131,940.950000,918.735656,929.400000,929.086066,929.381721,6.926324e+06,5.803935e+14,156046.081967,3.903821e+06,0.575982
2019-1,729.993443,730.260246,736.844672,723.549590,730.515164,730.592213,730.426557,8.080352e+06,5.878771e+14,156318.016393,4.678538e+06,0.576299
2019-2,752.087805,751.813821,759.780894,744.218699,752.178862,752.080894,752.244634,1.005291e+07,7.393320e+14,189516.634146,5.630831e+06,0.565012
2020-1,705.273577,704.788618,716.536179,694.970325,705.548374,705.312602,706.032602,1.001888e+07,6.905967e+14,181326.479675,4.926104e+06,0.492477
2020-2,1023.515504,1026.311240,1040.118992,1014.877519,1027.980233,1027.545349,1027.280775,1.150335e+07,1.175483e+15,203786.356589,4.781351e+06,0.442643
2021-1,1330.752500,1333.551875,1348.478125,1317.471250,1332.981250,1331.984375,1332.838625,8.597099e+06,1.150029e+15,208140.837500,4.225757e+06,0.498904

In [9]:
# plt.plot(INFYdf['Date'], INFYdf['Close'])
# plt.xlabel('Date')
# plt.ylabel('Close')
# plt.title('Line graph of Close over time')
# plt.show()